### ISSUE TITLE
Deprecated Farmer's Delight Support?

### ISSUE THREAD

**Issue by originalusername32** [Chailotl/pumpkin-pie#4]
Hey there! Basically what it says on the tin - would support for the [deprecated Farmer's Delight port](https://modrinth.com/mod/farmers-delight-fabric) for Fabric be possible? At the very least for 1.20.1. Thank you either way! Will definitely be using this mod at some point in the future xD

**Comment by Chailotl** [comment]
I think it's best to stick with the [refabricated Farmer's Delight port](https://modrinth.com/mod/farmers-delight-refabricated) and instead encourage other mod developers to switch to it. I'm not really interested in supporting deprecated mods so I'm closing this issue ^_^;
